version: '{build}'
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: dotnet pack .\src\Renci.SshNet.Abstractions\Renci.SshNet.Abstractions.csproj -c Release -o artifacts /nologo
test: off
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: BnreJniDdH2DF/eZeshLP/+BO27+3QImTK9Z1g+tn1Ci8ZKfcp1bOjcO9w2n0V7C
  on:
    branch: master
    appveyor_repo_tag: false